### ISSUE TITLE
Slight Confusion - Setup Questions

### ISSUE THREAD

**Issue by MikeP1990** [websavers/WHMCS-Google-Tag-Manager#16]
Hello,

Thank you so much for this module, it's saved me such a headache, still have a slight niggle though...

I see when enabling it there is the option to enable Data Layer, you then go on to mention about the trigger setup.

1. Do I need to configure the triggers if I have the Data Layer option enabled (and ecommerce enabled on the GA4 event).
2. If I do need to create them, I don't quite understand how they need to be setup, I've given my confusion below:

View Item (Event Name) - "view_item_list|select_item|view_item|add_to_cart|begin_checkout|purchase" and enable regex matching
view_item (Event Name) - "view_item_list|select_item|view_item|add_to_cart|begin_checkout|purchase" and enable regex matching
whmcs (Event Name) - "view_item_list|select_item|view_item|add_to_cart|begin_checkout|purchase" and enable regex matching

If 1 or 2, do they need to be created for each one and in the same fashion?

Any assistance would be greatly appreciated, there's a coffee in it for you :D

Thanks.

**Comment by jas8522** [comment]
If you don't create them, do you see the events triggered in Google Analytics? That would be the best way to answer question (1).

You only need to create one because the 'regex matching' ensures each of those events are individually recognized. They're separated by `|` because that's the regex OR operator.
